### ISSUE TITLE
Stylus clicks are not recognised by some software

### ISSUE THREAD

**Issue by Braintoe** [linuxwacom/xf86-input-wacom#304]
I hope I am at the right place since I literally have no clue on what might be the reason for this:

Some software such as the Teamviewer remote support software v15.25 and up (https://community.teamviewer.com/English/discussion/122230/linux-downgrade-to-version-15-27-3) and the - completely unrelated - Ultimaker Cura 3D slicer software seemingly since version 5.0 (https://github.com/Ultimaker/Cura/issues/12554, https://github.com/Ultimaker/Cura/issues/13707 and some others) does not recognise any click events that originate from the Wacom stylus.

Other software works perfectly fine at the same moment.

My setup is a Wacom PTH-651 on Linux Mint 21.1 with the standard Wacom driver provided by the system (currently 1:1.0.0-3ubuntu1) - the problem however survived two system upgrades since Linux Mint 20 when I updated to the mentioned Teamviewer version. Since other people are affected as well, I assume this is nothing specific to Linux Mint alone.

The PTH-651 also has Multitouch capabilities. If I use that and tap with a finger instead of the stylus, clicks are recognised correctly in both programs.

The only issue here I found that seemed to remtoly fit to my problem suggested to set the gesture parameter to "off" - but that is already the case on my computer.

Any hints on what to check or do to narrow down or maybe even solve this problem are highly appreciated.

**Comment by whot** [comment]
As a general rule: if an issue is only visible in one (or some specific) applications, it's not the driver since the driver has no clue if any application is even running - it just passes on events regardless and *where* those events are delivered is up to the X server.

So this is some event sequence that's disliked by those particular applications. A good start would be to check what actual events are submitted by the driver for a click event - the best/only way to do this is to run `xinput test-xi2` and click into that window.

If you have the git repo, you can build with the gwacom helper library enabled (see `meson.build` and the dependencies needed for `build_gwacom`) - that will give you `builddir/wacom-record` which records events from the driver but prints them instead of passing them to the X driver (only an approximage description). The output of that would be useful to see if there's anything specifically amiss - digging through xi2 output is hard.

**Comment by Braintoe** [comment]
I stuck with the xinput test-xi2 command for now. This is what I got:

A click with multitouch (finger) which is detected by the program:

```
EVENT type 15 (RawButtonPress)
    device: 2 (10)
    detail: 1
    flags: 
    valuators:

EVENT type 16 (RawButtonRelease)
    device: 2 (10)
    detail: 1
    flags: 
    valuators:
```

A click with the pen yielded the following results:

Pen vertically dropped some centimeters onto the tablet surface with the hand kept at a distance to minimise any disturbances (ignored by the program):
```
EVENT type 15 (RawButtonPress)
    device: 2 (8)
    detail: 1
    flags: 
    valuators:
          0: 16324.00 (16324.00)
          1: 15667.00 (15667.00)
          2: 42964.00 (42964.00)
          3: 0.00 (0.00)
          4: 4.00 (4.00)
          5: -900.00 (-900.00)


--------- numerous EVENT type 17 (RawMotion) events ----------


EVENT type 16 (RawButtonRelease)
    device: 2 (8)
    detail: 1
    flags: 
    valuators:
          0: 15986.00 (15986.00)
          1: 15339.00 (15339.00)
          2: 0.00 (0.00)
          3: 0.00 (0.00)
          4: 2.00 (2.00)
          5: -900.00 (-900.00)
```

And the same thing done with a mouse with deliberate motion while pressing the button to simulate pen behaviour (again, detected by the program):

```
EVENT type 15 (RawButtonPress)
    device: 2 (16)
    detail: 1
    flags: 
    valuators:

--------- numerous EVENT type 17 (RawMotion) events ----------

EVENT type 16 (RawButtonRelease)
    device: 2 (16)
    detail: 1
    flags: 
    valuators:
```

This tells me the events are there, but the software either fails due to the speed  of the motion events in between or (I guess more likely) due to the valuators... I will tell this to the program developers. Thank you very much!
